### PR TITLE
Headers and fancy async

### LINKED ISSUE #6: fancyAsync should implement Using and TryFinally
because you can't use `use` and `try/with` in routes atm.

### PR DESCRIPTION
**Pull request by albertjan**
fix #6 and some other stuff

### CODE REVIEW

**Comment by albertjan** [comment]
@simonhdickson could you have a look at this sometime?

**Comment by simonhdickson** [comment]
Needs to be merged :+1:

**Comment by albertjan** [comment]
or rebased :smile:

**Comment by albertjan** [comment]
I also fixed the build for mono and windows. You can just turn appveyor and travis on for this repo after this. See https://travis-ci.org/curit/Fancy and https://ci.appveyor.com/project/albertjan/fancy

**Comment by albertjan** [comment]
Thanks! :smile:

**Comment by simonhdickson** [comment]
Thank you for all this, and also mentioning about travis/appveyor, never actually used them before (I did know of them though).

**Comment by albertjan** [comment]
Thanks :smile:.

**Comment by albertjan** [comment]
You can turn them on for free for this repository. And add badges to the readme. Appveyor also adds a dev nuget package feed. It will automatically run the build for every PR.

**Pull request merged**
